In [1]:
import numpy as np #faster operation

list vs numpy - time taken


In [ ]:
from time import process_time
list=[i for i in range(10000)]
start_time=process_time()
list=[i+5 for i in list]
end_time=process_time()
print(end_time-start_time)

#timing of numpy array
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0018438879999997937
0.0002434159999999963


In [ ]:
#numpy array
list1=[1,2,3,4,5]
print(list1)
type(list1)

np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creatinf 1D array
a=np.array([1,2,3,4])
print(a)
print(a.shape) #telling how many rows and columns
#2D array
b=np.array([[1,2,3,4],[6,7,8,9]])
print(b)
b.shape

[1 2 3 4]
(4,)
[[1 2 3 4]
 [6 7 8 9]]


(2, 4)

In [ ]:
c=np.array([(1,2,3),(5,6,7),(8,9,10)],dtype=float) #defining data type
print(c)
c.shape

[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


(3, 3)

In [ ]:
#initial placeholders
# create numpy array of 0
d = np.zeros((2,3),dtype=int)
print(d)

#create numpy arrays of 1
e = np.ones((6,3),dtype=int)
print(e)

#with particular value
f=np.full((3,6),6.78)
print(f)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[6.78 6.78 6.78 6.78 6.78 6.78]
 [6.78 6.78 6.78 6.78 6.78 6.78]
 [6.78 6.78 6.78 6.78 6.78 6.78]]


In [ ]:
#create an identity matrix(in identity mat rows=col)
g=np.eye(4,dtype=float)
print(g)

#creating a numpy array with random values
h=np.random.random((3,4)) #will be b/w 0 and 1
print(h)

#random integers values array within a specific usage
i=np.random.randint(12,23,(2,3)) #this also applicable (12,23,size=(6,7))
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.70013758 0.63619484 0.83264103 0.34005844]
 [0.0342219  0.00546841 0.50256984 0.35299299]
 [0.61828279 0.85239519 0.55720117 0.6141471 ]]
[[20 20 17]
 [18 14 19]]


In [ ]:
#array with of evenly spaced values --> speciying the number of values required
j=np.linspace(10,40,4)
print(j)

#array of evenly spaced value --> specifying the step
k=np.arange(10,40,5) #it mean it inc by 5 like 10 15...35(n-1) terms


[10. 20. 30. 40.]
[10 15 20 25 30 35]


In [ ]:
#convert list to numpy array
list2=[10,20,30,40,50,60]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

#tuple to numpy array
tuple2=(10,20,30,40,50,60)
np_array=np.asarray(tuple2)
print(np_array)
type(np_array)

[10 20 30 40 50 60]
[10 20 30 40 50 60]


numpy.ndarray

analysing array

In [ ]:
#analysing a numpy array
l= np.random.randint(10,90,(5,5))
print(l)

#number of dimensions
print(l.ndim) #telling 1d/2d/3d/...

#number of elements
print(l.size)

#checking the data type
print(l.dtype)

NameError: name 'np' is not defined

In [ ]:
# mathematical operations on array
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #concatinate of 2 list

m=np.random.randint(10,20,(3,3))
n=np.random.randint(10,20,(3,3))
print(m)
print(n)
print(m+n)
print(m-n)
print(m*n)
print(m/n)





[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[10 17 17]
 [17 13 15]
 [14 15 16]]
[[10 14 12]
 [13 10 12]
 [18 18 12]]
[[20 31 29]
 [30 23 27]
 [32 33 28]]
[[ 0  3  5]
 [ 4  3  3]
 [-4 -3  4]]
[[100 238 204]
 [221 130 180]
 [252 270 192]]
[[1.         1.21428571 1.41666667]
 [1.30769231 1.3        1.25      ]
 [0.77777778 0.83333333 1.33333333]]


In [ ]:


print(np.add(m, n))  # Same as m + n
print(np.subtract(m, n))  # Same as m - n
print(np.multiply(m, n))  # Same as m * n
print(np.divide(m, n))  # Same as m / n
print(np.sqrt(m))  # Square root of each element in m
print(np.sqrt(n))  # Square root of each element in n
print(np.exp(m))  # Exponential of each element in m
print(np.exp(n))  # Exponential of each element in n

[[27 26 33]
 [28 30 23]
 [38 21 27]]
[[-1 -4  3]
 [-6 -2  1]
 [ 0 -1  5]]
[[182 165 270]
 [187 224 132]
 [361 110 176]]
[[0.92857143 0.73333333 1.2       ]
 [0.64705882 0.875      1.09090909]
 [1.         0.90909091 1.45454545]]
[[3.60555128 3.31662479 4.24264069]
 [3.31662479 3.74165739 3.46410162]
 [4.35889894 3.16227766 4.        ]]
[[3.74165739 3.87298335 3.87298335]
 [4.12310563 4.         3.31662479]
 [4.35889894 3.31662479 3.31662479]]
[[4.42413392e+05 5.98741417e+04 6.56599691e+07]
 [5.98741417e+04 1.20260428e+06 1.62754791e+05]
 [1.78482301e+08 2.20264658e+04 8.88611052e+06]]
[[1.20260428e+06 3.26901737e+06 3.26901737e+06]
 [2.41549528e+07 8.88611052e+06 5.98741417e+04]
 [1.78482301e+08 5.98741417e+04 5.98741417e+04]]


In [ ]:
#array manipulation
o=np.random.randint(10,30,(3,4))
print(o)

#transpose
p=np.transpose(o)
print(p)

#reshaping
q=o.reshape(6,2) #make sure that mltiplication of (col*rows) will be same
print(q)

[[16 20 21 17]
 [26 20 27 27]
 [14 14 23 27]]
[[16 26 14]
 [20 20 14]
 [21 27 23]
 [17 27 27]]
[[16 20]
 [21 17]
 [26 20]
 [27 27]
 [14 14]
 [23 27]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition, subtraction, etc.
print(arr1 + arr2)  # [5 7 9]
print(arr1 - arr2)  # [-3 -3 -3]
print(arr1 * arr2)  # [4 10 18]


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1, 2])   # Element at 2nd row, 3rd column (6)
print(arr2[:, 1])   # All rows, 2nd column (array of [2, 5, 8])


6
[2 5 8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # Sum of elements
print(np.mean(arr))    # Mean of elements
print(np.sin(arr))     # Sine of each element
print(np.sqrt(arr))    # Square root of each element


15
3.0
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication (dot product)
print(np.dot(mat1, mat2))
#[[1*5 + 2*7, 1*6 + 2*8],
#[3*5 + 4*7, 3*6 + 4*8]]
# Transpose
print(mat1.T)


NameError: name 'np' is not defined