In [3]:
import numpy as np


In [4]:
a=np.array([2,5])
b=np.array([3,1])
a_dor_b=np.dot(a,b)
print(a_dor_b) #DOT PRDT A1*A2+B1*B2
print(np.cross(a,b)) #CROSS PRDT A1*B2-B1*A2

11
-13


In [5]:
c=np.array([1,-2,3])
d=np.array([-4,5,6])
print(np.cross(c,d))

[-27 -18  -3]


In [6]:
#PROJECTION OF  "E" VECT ON "F" VECT
e=np.array([1,2,3])
f=np.array([4,5,6])
print(np.dot(e,f))
projection=np.dot(e,f)/np.dot(f,f)*f
print(projection)
projection1 = np.dot(e,f)/(np.linalg.norm(f)**2)*f
#np.linalg.norm(f): This function calculates the Euclidean norm (or magnitude) of vector f. The Euclidean norm is the square root of the sum of the squares of the vector's components.
#Mathematically: ||f|| = √(f₁² + f₂² + f₃²)
print(projection1)

32
[1.66233766 2.07792208 2.49350649]
[1.66233766 2.07792208 2.49350649]
