In [1]:
import numpy as np


In [2]:
#CREATING MATRIX USING MATRIX
MATRIX_1= np.array([[2,3],[6,7]])
MATRIX_2= np.array([[4,5,56,78],[8,9,67,33],[23,56,11,99]])
print(MATRIX_1)
print(MATRIX_2)
MATRIX_1.shape
MATRIX_2.shape

[[2 3]
 [6 7]]
[[ 4  5 56 78]
 [ 8  9 67 33]
 [23 56 11 99]]


(3, 4)

In [3]:
#CREATING MATRICES WITH RANDOM VALUES
matrix_3=np.random.randint(23,30,size=(3,4))
matrix_3

array([[28, 23, 23, 24],
       [24, 27, 24, 23],
       [28, 24, 26, 27]])

In [7]:
from re import I
#MATRIX ALL 1 VALUES
matrix_4=np.ones((3,4),dtype=int)
matrix_4
print(matrix_4)
#MATRIX ALL 0 VALUES
matrix_5=np.zeros((3,4),dtype=float)
matrix_5

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#identy matrix                 #diagonal values are 1
matrix_6=np.eye(4)
matrix_6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
matrix_to_transpose = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_to_transpose)
matrix_7 = np.transpose(matrix_to_transpose)
print(matrix_7)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
