In [18]:
#matrix operation
import numpy as np


In [19]:
mat1=np.array([[1,0,3],[4,5,6],[7,0,9]])
mat2=np.array([[1,9,3],[4,9,6],[1,8,9]])
mat3=np.add(mat1,mat2)
mat3

array([[ 2,  9,  6],
       [ 8, 14, 12],
       [ 8,  8, 18]])

In [21]:
mat4=np.subtract(mat1,mat2)
mat4

array([[ 0, -9,  0],
       [ 0, -4,  0],
       [ 6, -8,  0]])

In [22]:

mat5 = np.array([[2, 4, 5], [3, 6, 8], [1, 1, 1], [9, 9, 9], [2, 2, 2]])  # 5x3
mat6 = np.array([[2, 4, 5], [3, 6, 8], [1, 1, 1]])  # 3x3

mat7 = np.dot(mat5, mat6)  # 5x3

print(mat7)

[[ 21  37  47]
 [ 32  56  71]
 [  6  11  14]
 [ 54  99 126]
 [ 12  22  28]]


In [23]:
#multiplication  #shold have same dimensions
mat8=np.multiply(mat1,mat2)
mat8

array([[ 1,  0,  9],
       [16, 45, 36],
       [ 7,  0, 81]])